export const FETCH_STORIES_LOADING = "FETCH_STORIES_LOADING";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";
export const SEARCH_QUERY = "SEARCH_QUERY"
export const CLEAR_STORIES = "CLEAR_STORIES"