export const FETCH_STORIES_LOADING = "FETCH_STORIES_LOADING";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";
export const SEARCH_QUERY = "SEARCH_QUERY"
export const CLEAR_STORIES = "CLEAR_STORIES"
export const LOAD_MORE = "LOAD_MORE"
export const CLEAR_QUERY = "CLEAR_QUERY"
export const NO_STORIES_FOUND = "NO_STORIES_FOUND"